### PR TITLE
Codespaces  updates

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
# What is the feature?
Updating the codespaces file, addresses #30 

# How have you implemented the solution?
* removes TMBhelper (which was causing builds to fail, even on main)
* Adds a message describing how to use rstudio, and how to install reshape2
* Installs gdb

# Does the PR impact any other area of the project, maybe another repo?
* There may still be some case studies that require TMBhelper

### CODE REVIEW

**Review by kellijohnson-NOAA — APPROVED** [review]
I thought that gdb was installed in the code spaces so I do not understand the message on lines 9--12 in the .devcontainer/welcome.txt. Other than that, the PR looks good and can be merged in whenever you want @k-doering-NOAA.

**Comment by kellijohnson-NOAA** [comment]
We could get rid of the calls to `reshape2::melt()` using
```
  x1 <- ...
  test <- tibble::rownames_to_column(
    dplyr::as_tibble(x1),
    var = "year"
  ) |>
    tidyr::pivot_longer(
      cols = -year,
      names_to = "age",
      values_to = "paa"
    )
```
but I do not think that it is needed because the output will be "pre-formatted" soon and the large majority of this code can go away throughout all of the case studies. So, I would rather focus on creating the output for everyone in the future than worrying about changing the case-study code to not use reshape2 right now. The solution of a warning in the welcome message is perfect.

**Comment by k-doering-NOAA** [comment]
> I thought that gdb was installed in the code spaces so I do not understand the message on lines 9--12 in the .devcontainer/welcome.txt. Other than that, the PR looks good and can be merged in whenever you want @k-doering-NOAA.

Thanks @kellijohnson-NOAA , I double-checked, and lines 9-12 in `.devcontainer/welcome.txt` was removed in a later commit (when I successfully installed gdb), even though it shows up in 78346f771056b5cd7e518df41c8eabd6539d319a

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA ... I always get the order of the commits backwards on PR and think that I should look at them from bottom to top rather than top to bottom.

**Pull request merged**
