### PR TITLE
Update _quarto.yml

### PR DESCRIPTION
**Pull request by ChristineStawitz-NOAA**
make the Github link on the sidebar go to the case studies repo rather than nmfs-opensci

# What is the feature?
*  The Github icon on the sidebar went to nmfs-opensci github repo instead of the FIMS case studies one

# How have you implemented the solution?
* changed the link target

# Does the PR impact any other area of the project, maybe another repo?
* no

### CODE REVIEW

**Review by kellijohnson-NOAA — APPROVED** [review]
Thanks @ChristineStawitz-NOAA this is great and thanks, I think, to @curryc2 for noticing during the FIMS Council Meeting.

**Comment by kellijohnson-NOAA** [comment]
I am not sure why petrale failed in the test, I will check before I merge.

**Comment by iantaylor-NOAA** [comment]
The github action failure in the petrale case study is due to a change in r4ss that I should have sorted out here already. I will fix it tomorrow.

**Comment by kellijohnson-NOAA** [comment]
Thank you @iantaylor-NOAA

**Comment by iantaylor-NOAA** [comment]
Fix was more complex than expected, but changes in https://github.com/NOAA-FIMS/case-studies/pull/48 got things working.

**Comment by kellijohnson-NOAA** [comment]
Thanks @ChristineStawitz-NOAA and @iantaylor-NOAA for these fixes. FYI @iantaylor-NOAA I brought in the changes from #48 into this PR using git cherry-pick and then I squashed them into a single commit instead of merging because your PR has a merge in it and I would like to keep merge commits out of repos in the NOAA-FIMS organization.

**Pull request merged**
